
### Plik konfiguracyjny: `config.yaml`

```yaml
data_dir: 'data/'                   # Katalog z danymi do analizy
exclude_file: 'exclude_list.txt'     # Plik z listą wykluczeń
output_dir: 'output/'                # Katalog, gdzie zapisywane są wyniki
sampling_frequency: 1000             # Częstotliwość próbkowania danych
num_functions: 10                    # Liczba funkcji autokorelacyjnych
samples_per_function: 1024           # Liczba próbek na funkcję
log_file: 'spectrum_analysis.log'    # Plik z logami
log_level: 'INFO'                    # Poziom logowania
fft_type: 'rfft'                     # Typ FFT: fft, rfft, dct
report_file: 'raport.html'           # Plik wyjściowy z raportem HTML
